version: "3.8"

services:
    ordkupan-db:
        image: postgres:15.3
        environment:
            POSTGRES_USER: ordkupan
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ordkupan
        ports:
            - "5432:5432"
        volumes:
            - ordkupan-data:/var/lib/postgresql/data

volumes:
    ordkupan-data:
